USE spring_batch_demo;

SHOW TABLES;

select * from employees;

delete from employees where id in (201, 202, 203, 204, 205);

SELECT
    JOB_INSTANCE_ID,
    JOB_NAME,
    JOB_KEY
FROM BATCH_JOB_INSTANCE;

SELECT
    JOB_EXECUTION_ID,
    JOB_INSTANCE_ID,
    STATUS,
    EXIT_CODE
FROM BATCH_JOB_EXECUTION;

SELECT
    JOB_EXECUTION_ID,
    STATUS,
    READ_COUNT,
    WRITE_COUNT,
    FILTER_COUNT,
    PROCESS_SKIP_COUNT,
    WRITE_SKIP_COUNT,
    ROLLBACK_COUNT
FROM BATCH_STEP_EXECUTION
ORDER BY STEP_EXECUTION_ID;

SELECT * FROM BATCH_JOB_INSTANCE;

SELECT * FROM BATCH_JOB_EXECUTION;

SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;

SELECT * FROM BATCH_STEP_EXECUTION;


TRUNCATE TABLE employees;

DELETE FROM employees;
SET SQL_SAFE_UPDATES = 0;